repoURL: https://github.com/Jyejin/build-monitoring-system

apps:
  - name: argocd
    namespace: argocd
  - name: nginx
    namespace: default
  - name: eck-elasticsearch
    namespace: elastic
  - name: eck-kibana
    namespace: elastic